title: Mengkun's Homepage
page-top-title: Mengkun Liang
top-section-bg-text: Everything happens for the best.
home-subtitle: Mengkun Liang
copyright-text: '&copy; DigML 2025-future. All Rights Reserved.'
